Initial modification to Tradheli guide
ArduPilot/MethodicConfigurator pull request #44
Opened 2024-09-02 04:11 UTC by bnsgeyer

Here is the start of modification to the Tradheli guide.

2024-09-02 09:04 UTC, amilcarlucas commented on TUNING_GUIDE_Heli.md
> -![eCalc example screenshot](images/blog/eCalc_(en).PNG)
There is ecalc Heli

so just replace multirotor with heli

2024-09-02 09:05 UTC, amilcarlucas requested changes
Nice, thanks for helping out with this

2024-09-02 09:09 UTC, amilcarlucas commented
https://github.com/ArduPilot/MethodicConfigurator/releases/tag/latest contains a Heli OMP_M4 template that @allister is working on. Should we use that instead of the Trex500 ?

2024-09-02 18:00 UTC, Allister779 commented
Let me know if you want any changes to the OMP_M4 files.

2024-10-30 13:58 UTC, amilcarlucas commented
I did the changes locally (I could not push to your repo) and merged this one. Please create a new one to continue to work on this

2024-10-30 13:58 UTC, closed without merging